[project]
name = "rogue-scroll"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jeffrey Goldberg", email = "jeffrey@goldmark.org" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
rogue-scroll = "rogue_scroll:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
